
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'customer_analysis'
version: '1.0.0'
config-version: 2

vars:
    order_year: "2017"

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

on-run-start: "insert into package_audit_tb(run_status,run_end_time,package_name,invocation_id) values('started',null,'customer','{{invocation_id}}');commit;"
on-run-end: "update package_audit_tb set run_status='completed',run_end_time=current_timestamp
            where  package_name = 'customer' and  run_status='started';commit;"

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
    #pre-hook: "insert into DBT_INTEGRATION.PUBLIC.AUDIT(status,run_end_time) values('model_started',null);commit;"
    #post-hook: "update DBT_INTEGRATION.PUBLIC.AUDIT set status='model_completed',run_end_time=current_timestamp
    #       where id=(select max(id) from DBT_INTEGRATION.PUBLIC.AUDIT where status='model_started');commit;"
    pre-hook: "{{ model_audit_start(this)}}"
    post-hook: "{{ model_audit_end(this) }}"
    customer_analysis:
      # Applies to all files under models/example/
      #example:
          materialized: view
          +transient: false
#         schema: staging
 #         schema: core

#seeds:
#    schema: core
          
