version: 2

models:
    - name: statewise_order_count
      description: "A state wise order count"
      columns:
          - name: STATE_NAME
            description: "The state name for this table"
            tests:
                - unique
                - not_null

    - name: monthwise_order_perc
      description: '{{ doc("order_perc")}}'
      columns:
          - name: MONTHLY_ORDER_PERCENTAGE
            tests:
                - not_null
                - dbt_utils.not_constant
                - perc_check
                
