version: 2

sources:
  - name: source_test
    database: DBT_INTEGRATION
    schema: public
    tables:
      - name: state
      - name: customer
        columns:
          - name: CUSTOMER_ORDER_ID
            tests:
              - unique
              - not_null
      - name: orders
        freshness: 
          warn_after: {count: 6, period: hour}
          error_after: {count: 12, period: hour}
        loaded_at_field: ORDER_PURCHASE_TIMESTAMP
        columns:
          - name: ORDER_ID
            tests:
              - unique
              - not_null

     